package space.wangjiang.summer.model.bean;

import space.wangjiang.summer.model.Model;

/**
 * Generated by Summer, you should not modify this file.
 */
public abstract class BlogBean<M extends BlogBean<M>> extends Model<M> {

    public void setId(java.lang.Integer id) {
        set("id", id);
    }

    public java.lang.Integer getId() {
        return (java.lang.Integer) get("id");
    }

    public void setUserId(java.lang.Integer userId) {
        set("user_id", userId);
    }

    public java.lang.Integer getUserId() {
        return (java.lang.Integer) get("user_id");
    }

    public void setTitle(java.lang.String title) {
        set("title", title);
    }

    public java.lang.String getTitle() {
        return (java.lang.String) get("title");
    }

    public void setContent(java.lang.String content) {
        set("content", content);
    }

    public java.lang.String getContent() {
        return (java.lang.String) get("content");
    }

}