package space.wangjiang.summer.model.bean;

import space.wangjiang.summer.model.Model;

/**
 * Generated by Summer, you should not modify this file.
 */
public abstract class UserBean<M extends UserBean<M>> extends Model<M> {

    public void setId(java.lang.Integer id) {
        set("id", id);
    }

    public java.lang.Integer getId() {
        return (java.lang.Integer) get("id");
    }

    public void setUsername(java.lang.String username) {
        set("username", username);
    }

    public java.lang.String getUsername() {
        return (java.lang.String) get("username");
    }

    public void setEmail(java.lang.String email) {
        set("email", email);
    }

    public java.lang.String getEmail() {
        return (java.lang.String) get("email");
    }

    public void setAge(java.lang.Integer age) {
        set("age", age);
    }

    public java.lang.Integer getAge() {
        return (java.lang.Integer) get("age");
    }

    public void setPassword(java.lang.String password) {
        set("password", password);
    }

    public java.lang.String getPassword() {
        return (java.lang.String) get("password");
    }

}