package space.wangjiang.summer.model;

import space.wangjiang.summer.model.ModelConfig;

/**
 * Generated by Summer, you should not modify this file.
 */
public class MappingKit {

    public static void mapping(ModelConfig config) {
        config.addMapping("blog", "id", Blog.class);
        config.addMapping("like", "blog_id,user_id", Like.class);
        config.addMapping("user", "id", User.class);
    }

}